# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_polet.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowADD_POLET(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.setFixedSize(500,430)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(245, 245, 245);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_ADD_POLET = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_ADD_POLET.setGeometry(QtCore.QRect(10, 10, 471, 331))
        self.groupBox_ADD_POLET.setMaximumSize(QtCore.QSize(16777215, 700))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.groupBox_ADD_POLET.setFont(font)
        self.groupBox_ADD_POLET.setObjectName("groupBox_ADD_POLET")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_ADD_POLET)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 40, 451, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_ZATRACHENO_TOPLIVO = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_ZATRACHENO_TOPLIVO.setStyleSheet("QLineEdit{\n"
"    background-color:white;\n"
"}\n"
"QLineEdit:hover{\n"
"    border:1px solid rgb(5,142,215);\n"
"}\n"
"QLineEdit:pressed{\n"
"    border:1px solid rgb(5,142,215);\n"
"}")
        self.lineEdit_ZATRACHENO_TOPLIVO.setObjectName("lineEdit_ZATRACHENO_TOPLIVO")
        self.gridLayout.addWidget(self.lineEdit_ZATRACHENO_TOPLIVO, 6, 1, 1, 1)
        self.label_VIVEDEN_IS_STOIA = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_VIVEDEN_IS_STOIA.setFont(font)
        self.label_VIVEDEN_IS_STOIA.setObjectName("label_VIVEDEN_IS_STOIA")
        self.gridLayout.addWidget(self.label_VIVEDEN_IS_STOIA, 5, 0, 1, 1)
        self.lineEdit_ID_BPLA = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ID_BPLA.sizePolicy().hasHeightForWidth())
        self.lineEdit_ID_BPLA.setSizePolicy(sizePolicy)
        self.lineEdit_ID_BPLA.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_ID_BPLA.setStyleSheet("QLineEdit{\n"
"    background-color:white;\n"
"}\n"
"QLineEdit:hover{\n"
"    border:1px solid rgb(5,142,215);\n"
"}\n"
"QLineEdit:pressed{\n"
"    border:1px solid rgb(5,142,215);\n"
"}")
        self.lineEdit_ID_BPLA.setText("")
        self.lineEdit_ID_BPLA.setObjectName("lineEdit_ID_BPLA")
        self.gridLayout.addWidget(self.lineEdit_ID_BPLA, 0, 1, 1, 1)
        self.lineEdit_BOEVIE_TASKS_COMPLETE = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_BOEVIE_TASKS_COMPLETE.setStyleSheet("QLineEdit{\n"
"    background-color:white;\n"
"}\n"
"QLineEdit:hover{\n"
"    border:1px solid rgb(5,142,215);\n"
"}\n"
"QLineEdit:pressed{\n"
"    border:1px solid rgb(5,142,215);\n"
"}")
        self.lineEdit_BOEVIE_TASKS_COMPLETE.setObjectName("lineEdit_BOEVIE_TASKS_COMPLETE")
        self.gridLayout.addWidget(self.lineEdit_BOEVIE_TASKS_COMPLETE, 4, 1, 1, 1)
        self.lineEdit_MAX_HEIGHT_FLIGHT = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_MAX_HEIGHT_FLIGHT.setStyleSheet("QLineEdit{\n"
"    background-color:white;\n"
"}\n"
"QLineEdit:hover{\n"
"    border:1px solid rgb(5,142,215);\n"
"}\n"
"QLineEdit:pressed{\n"
"    border:1px solid rgb(5,142,215);\n"
"}")
        self.lineEdit_MAX_HEIGHT_FLIGHT.setObjectName("lineEdit_MAX_HEIGHT_FLIGHT")
        self.gridLayout.addWidget(self.lineEdit_MAX_HEIGHT_FLIGHT, 3, 1, 1, 1)
        self.lineEdit_DIST_POLET = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_DIST_POLET.setStyleSheet("QLineEdit{\n"
"    background-color:white;\n"
"}\n"
"QLineEdit:hover{\n"
"    border:1px solid rgb(5,142,215);\n"
"}\n"
"QLineEdit:pressed{\n"
"    border:1px solid rgb(5,142,215);\n"
"}")
        self.lineEdit_DIST_POLET.setText("")
        self.lineEdit_DIST_POLET.setObjectName("lineEdit_DIST_POLET")
        self.gridLayout.addWidget(self.lineEdit_DIST_POLET, 2, 1, 1, 1)
        self.label_2_FLIGHT_TIME_POLET = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2_FLIGHT_TIME_POLET.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_2_FLIGHT_TIME_POLET.setFont(font)
        self.label_2_FLIGHT_TIME_POLET.setObjectName("label_2_FLIGHT_TIME_POLET")
        self.gridLayout.addWidget(self.label_2_FLIGHT_TIME_POLET, 1, 0, 1, 1)
        self.label_DIST_POLET = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_DIST_POLET.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_DIST_POLET.setFont(font)
        self.label_DIST_POLET.setObjectName("label_DIST_POLET")
        self.gridLayout.addWidget(self.label_DIST_POLET, 2, 0, 1, 1)
        self.label_MAX_HEIGHT_FLIGHT = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_MAX_HEIGHT_FLIGHT.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_MAX_HEIGHT_FLIGHT.setFont(font)
        self.label_MAX_HEIGHT_FLIGHT.setObjectName("label_MAX_HEIGHT_FLIGHT")
        self.gridLayout.addWidget(self.label_MAX_HEIGHT_FLIGHT, 3, 0, 1, 1)
        self.label_BOEVIE_TASKS_COMPLETE = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_BOEVIE_TASKS_COMPLETE.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_BOEVIE_TASKS_COMPLETE.setFont(font)
        self.label_BOEVIE_TASKS_COMPLETE.setObjectName("label_BOEVIE_TASKS_COMPLETE")
        self.gridLayout.addWidget(self.label_BOEVIE_TASKS_COMPLETE, 4, 0, 1, 1)
        self.label_ZATRACHENNOE_TOPLIVO = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_ZATRACHENNOE_TOPLIVO.setFont(font)
        self.label_ZATRACHENNOE_TOPLIVO.setObjectName("label_ZATRACHENNOE_TOPLIVO")
        self.gridLayout.addWidget(self.label_ZATRACHENNOE_TOPLIVO, 6, 0, 1, 1)
        self.label_ID_BPLA = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_ID_BPLA.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_ID_BPLA.setFont(font)
        self.label_ID_BPLA.setObjectName("label_ID_BPLA")
        self.gridLayout.addWidget(self.label_ID_BPLA, 0, 0, 1, 1)
        self.lineEdit__FLIGHT_TIME_POLET = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit__FLIGHT_TIME_POLET.setStyleSheet("QLineEdit{\n"
"    background-color:white;\n"
"}\n"
"QLineEdit:hover{\n"
"    border:1px solid rgb(5,142,215);\n"
"}\n"
"QLineEdit:pressed{\n"
"    border:1px solid rgb(5,142,215);\n"
"}")
        self.lineEdit__FLIGHT_TIME_POLET.setText("")
        self.lineEdit__FLIGHT_TIME_POLET.setObjectName("lineEdit__FLIGHT_TIME_POLET")
        self.gridLayout.addWidget(self.lineEdit__FLIGHT_TIME_POLET, 1, 1, 1, 1)
        self.checkBox_VIVEDEN_IS_STOROIA = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_VIVEDEN_IS_STOROIA.setStyleSheet("QPushButton{\n"
"background-color: rgb(215, 215, 215);\n"
"border: 1px solid gray;\n"
"}\n"
"QPushButton:hover {border:2px solid  rgb(0, 120, 215);}\n"
"QPushButton:pressed {border:2px solid  rgb(0, 120, 215);}")
        self.checkBox_VIVEDEN_IS_STOROIA.setText("")
        self.checkBox_VIVEDEN_IS_STOROIA.setObjectName("checkBox_VIVEDEN_IS_STOROIA")
        self.gridLayout.addWidget(self.checkBox_VIVEDEN_IS_STOROIA, 5, 1, 1, 1)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 350, 471, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_ADD_POLET_IN_BD = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_ADD_POLET_IN_BD.setFont(font)
        self.pushButton_ADD_POLET_IN_BD.setStyleSheet("QPushButton{\n"
"background-color: rgb(215, 215, 215);\n"
"border: 1px solid gray;\n"
"}\n"
"QPushButton:hover {border:2px solid  rgb(0, 120, 215);}\n"
"QPushButton:pressed {border:2px solid  rgb(0, 120, 215);}")
        self.pushButton_ADD_POLET_IN_BD.setObjectName("pushButton_ADD_POLET_IN_BD")
        self.horizontalLayout.addWidget(self.pushButton_ADD_POLET_IN_BD)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 24))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.menu.setFont(font)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Добавить полет"))
        self.groupBox_ADD_POLET.setTitle(_translate("MainWindow", "Полет"))
        self.label_VIVEDEN_IS_STOIA.setText(_translate("MainWindow", "Выведен из строя"))
        self.label_2_FLIGHT_TIME_POLET.setText(_translate("MainWindow", "Время полета, с"))
        self.label_DIST_POLET.setText(_translate("MainWindow", "Дистанция полета, м"))
        self.label_MAX_HEIGHT_FLIGHT.setText(_translate("MainWindow", "Максимальная высота полета, м"))
        self.label_BOEVIE_TASKS_COMPLETE.setText(_translate("MainWindow", "<html><head/><body><p>Боевых задач выполнено</p></body></html>"))
        self.label_ZATRACHENNOE_TOPLIVO.setText(_translate("MainWindow", "Затраченное топливо на полет, л"))
        self.label_ID_BPLA.setText(_translate("MainWindow", "Идентификатор БПЛА"))
        self.pushButton_ADD_POLET_IN_BD.setText(_translate("MainWindow", "Добавить"))
        self.menu.setTitle(_translate("MainWindow", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindowADD_POLET()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
