# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_bpla.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindowADD(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.setFixedSize(500,430)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_ADD_BPLA = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_ADD_BPLA.setGeometry(QtCore.QRect(10, 10, 471, 331))
        self.groupBox_ADD_BPLA.setMaximumSize(QtCore.QSize(16777215, 700))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.groupBox_ADD_BPLA.setFont(font)
        self.groupBox_ADD_BPLA.setObjectName("groupBox_ADD_BPLA")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_ADD_BPLA)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 40, 451, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_MAX_FLIGHTS_TIME_BPLA = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_MAX_FLIGHTS_TIME_BPLA.setStyleSheet("QLineEdit{\n"
"    background-color:white;\n"
"}\n"
"QLineEdit:hover{\n"
"    border:1px solid rgb(5,142,215);\n"
"}\n"
"QLineEdit:pressed{\n"
"    border:1px solid rgb(5,142,215);\n"
"}")
        self.lineEdit_MAX_FLIGHTS_TIME_BPLA.setObjectName("lineEdit_MAX_FLIGHTS_TIME_BPLA")
        self.gridLayout.addWidget(self.lineEdit_MAX_FLIGHTS_TIME_BPLA, 5, 1, 1, 1)
        self.lineEdit_MAX_FLIGHTS_DIST_BPLA = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_MAX_FLIGHTS_DIST_BPLA.setStyleSheet("QLineEdit{\n"
"    background-color:white;\n"
"}\n"
"QLineEdit:hover{\n"
"    border:1px solid rgb(5,142,215);\n"
"}\n"
"QLineEdit:pressed{\n"
"    border:1px solid rgb(5,142,215);\n"
"}")
        self.lineEdit_MAX_FLIGHTS_DIST_BPLA.setObjectName("lineEdit_MAX_FLIGHTS_DIST_BPLA")
        self.gridLayout.addWidget(self.lineEdit_MAX_FLIGHTS_DIST_BPLA, 6, 1, 1, 1)
        self.label_MAX_FLIGHT_TIME_BPLA = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_MAX_FLIGHT_TIME_BPLA.setFont(font)
        self.label_MAX_FLIGHT_TIME_BPLA.setObjectName("label_MAX_FLIGHT_TIME_BPLA")
        self.gridLayout.addWidget(self.label_MAX_FLIGHT_TIME_BPLA, 5, 0, 1, 1)
        self.lineEdit_NAIMENOVANIE_BPLA = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_NAIMENOVANIE_BPLA.sizePolicy().hasHeightForWidth())
        self.lineEdit_NAIMENOVANIE_BPLA.setSizePolicy(sizePolicy)
        self.lineEdit_NAIMENOVANIE_BPLA.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_NAIMENOVANIE_BPLA.setStyleSheet("QLineEdit{\n"
"    background-color:white;\n"
"}\n"
"QLineEdit:hover{\n"
"    border:1px solid rgb(5,142,215);\n"
"}\n"
"QLineEdit:pressed{\n"
"    border:1px solid rgb(5,142,215);\n"
"}")
        self.lineEdit_NAIMENOVANIE_BPLA.setText("")
        self.lineEdit_NAIMENOVANIE_BPLA.setObjectName("lineEdit_NAIMENOVANIE_BPLA")
        self.gridLayout.addWidget(self.lineEdit_NAIMENOVANIE_BPLA, 0, 1, 1, 1)
        self.lineEdit_MAX_SPEED_BPLA = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_MAX_SPEED_BPLA.setStyleSheet("QLineEdit{\n"
"    background-color:white;\n"
"}\n"
"QLineEdit:hover{\n"
"    border:1px solid rgb(5,142,215);\n"
"}\n"
"QLineEdit:pressed{\n"
"    border:1px solid rgb(5,142,215);\n"
"}")
        self.lineEdit_MAX_SPEED_BPLA.setObjectName("lineEdit_MAX_SPEED_BPLA")
        self.gridLayout.addWidget(self.lineEdit_MAX_SPEED_BPLA, 4, 1, 1, 1)
        self.lineEdit_VES_BPLA = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_VES_BPLA.setStyleSheet("QLineEdit{\n"
"    background-color:white;\n"
"}\n"
"QLineEdit:hover{\n"
"    border:1px solid rgb(5,142,215);\n"
"}\n"
"QLineEdit:pressed{\n"
"    border:1px solid rgb(5,142,215);\n"
"}")
        self.lineEdit_VES_BPLA.setObjectName("lineEdit_VES_BPLA")
        self.gridLayout.addWidget(self.lineEdit_VES_BPLA, 3, 1, 1, 1)
        self.lineEdit_ZAVODSKOI_NOMER_BPLA = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_ZAVODSKOI_NOMER_BPLA.setStyleSheet("QLineEdit{\n"
"    background-color:white;\n"
"}\n"
"QLineEdit:hover{\n"
"    border:1px solid rgb(5,142,215);\n"
"}\n"
"QLineEdit:pressed{\n"
"    border:1px solid rgb(5,142,215);\n"
"}")
        self.lineEdit_ZAVODSKOI_NOMER_BPLA.setText("")
        self.lineEdit_ZAVODSKOI_NOMER_BPLA.setObjectName("lineEdit_ZAVODSKOI_NOMER_BPLA")
        self.gridLayout.addWidget(self.lineEdit_ZAVODSKOI_NOMER_BPLA, 2, 1, 1, 1)
        self.label_MODEL_BPLA = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_MODEL_BPLA.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_MODEL_BPLA.setFont(font)
        self.label_MODEL_BPLA.setObjectName("label_MODEL_BPLA")
        self.gridLayout.addWidget(self.label_MODEL_BPLA, 1, 0, 1, 1)
        self.label_ZAVODSKOI_NOMER_BPLA = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_ZAVODSKOI_NOMER_BPLA.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_ZAVODSKOI_NOMER_BPLA.setFont(font)
        self.label_ZAVODSKOI_NOMER_BPLA.setObjectName("label_ZAVODSKOI_NOMER_BPLA")
        self.gridLayout.addWidget(self.label_ZAVODSKOI_NOMER_BPLA, 2, 0, 1, 1)
        self.label_VES_BPLA = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_VES_BPLA.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_VES_BPLA.setFont(font)
        self.label_VES_BPLA.setObjectName("label_VES_BPLA")
        self.gridLayout.addWidget(self.label_VES_BPLA, 3, 0, 1, 1)
        self.label_MAX_SPEED_BPLA = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_MAX_SPEED_BPLA.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_MAX_SPEED_BPLA.setFont(font)
        self.label_MAX_SPEED_BPLA.setObjectName("label_MAX_SPEED_BPLA")
        self.gridLayout.addWidget(self.label_MAX_SPEED_BPLA, 4, 0, 1, 1)
        self.label_MAX_FLIGHT_DIST_BPLA = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_MAX_FLIGHT_DIST_BPLA.setFont(font)
        self.label_MAX_FLIGHT_DIST_BPLA.setObjectName("label_MAX_FLIGHT_DIST_BPLA")
        self.gridLayout.addWidget(self.label_MAX_FLIGHT_DIST_BPLA, 6, 0, 1, 1)
        self.label_NAIMENOVANIE = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_NAIMENOVANIE.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_NAIMENOVANIE.setFont(font)
        self.label_NAIMENOVANIE.setObjectName("label_NAIMENOVANIE")
        self.gridLayout.addWidget(self.label_NAIMENOVANIE, 0, 0, 1, 1)
        self.lineEdit_MODEL_BPLA = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_MODEL_BPLA.setStyleSheet("QLineEdit{\n"
"    background-color:white;\n"
"}\n"
"QLineEdit:hover{\n"
"    border:1px solid rgb(5,142,215);\n"
"}\n"
"QLineEdit:pressed{\n"
"    border:1px solid rgb(5,142,215);\n"
"}")
        self.lineEdit_MODEL_BPLA.setText("")
        self.lineEdit_MODEL_BPLA.setObjectName("lineEdit_MODEL_BPLA")
        self.gridLayout.addWidget(self.lineEdit_MODEL_BPLA, 1, 1, 1, 1)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 350, 471, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_ADD_BPLA_IN_BD = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_ADD_BPLA_IN_BD.setFont(font)
        self.pushButton_ADD_BPLA_IN_BD.setStyleSheet("QPushButton{\n"
"background-color: rgb(215, 215, 215);\n"
"border: 1px solid gray;\n"
"}\n"
"QPushButton:hover {border:2px solid  rgb(0, 120, 215);}\n"
"QPushButton:pressed {border:2px solid  rgb(0, 120, 215);}")
        self.pushButton_ADD_BPLA_IN_BD.setObjectName("pushButton_ADD_BPLA_IN_BD")
        self.horizontalLayout.addWidget(self.pushButton_ADD_BPLA_IN_BD)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 24))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.menu.setFont(font)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Добавить БПЛА"))
        self.groupBox_ADD_BPLA.setTitle(_translate("MainWindow", "БПЛА"))
        self.label_MAX_FLIGHT_TIME_BPLA.setText(_translate("MainWindow", "Максимальное времая полета, мин"))
        self.label_MODEL_BPLA.setText(_translate("MainWindow", "Модель"))
        self.label_ZAVODSKOI_NOMER_BPLA.setText(_translate("MainWindow", "Заводской номер"))
        self.label_VES_BPLA.setText(_translate("MainWindow", "Вес, кг"))
        self.label_MAX_SPEED_BPLA.setText(_translate("MainWindow", "<html><head/><body><p>Максимальная скорость, км\\ч</p></body></html>"))
        self.label_MAX_FLIGHT_DIST_BPLA.setText(_translate("MainWindow", "Максимальная дальность полет, м"))
        self.label_NAIMENOVANIE.setText(_translate("MainWindow", "Наименование"))
        self.pushButton_ADD_BPLA_IN_BD.setText(_translate("MainWindow", "Добавить"))
        self.menu.setTitle(_translate("MainWindow", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindowADD()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
