# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analitika_po_jivuchesti.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_Jivuchest(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(363, 245)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_PARAMETRI_ANALITIKI = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_PARAMETRI_ANALITIKI.setGeometry(QtCore.QRect(10, 10, 341, 201))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.groupBox_PARAMETRI_ANALITIKI.setFont(font)
        self.groupBox_PARAMETRI_ANALITIKI.setObjectName("groupBox_PARAMETRI_ANALITIKI")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_PARAMETRI_ANALITIKI)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 321, 111))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_SORT_PO = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.comboBox_SORT_PO.setFont(font)
        self.comboBox_SORT_PO.setStyleSheet("QComboBox{\n"
"    background-color:white;\n"
"}\n"
"QComboBox:hover{\n"
"    border:1px solid rgb(5,142,215);\n"
"}\n"
"QComboBox:pressed{\n"
"    border:1px solid rgb(5,142,215);\n"
"}")
        self.comboBox_SORT_PO.setObjectName("comboBox_SORT_PO")
        self.comboBox_SORT_PO.addItem("")
        self.comboBox_SORT_PO.addItem("")
        self.gridLayout.addWidget(self.comboBox_SORT_PO, 0, 1, 1, 1)
        self.label_SORT_PO = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_SORT_PO.setFont(font)
        self.label_SORT_PO.setObjectName("label_SORT_PO")
        self.gridLayout.addWidget(self.label_SORT_PO, 0, 0, 1, 1)
        self.label_VIBOR_MODEL = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_VIBOR_MODEL.setFont(font)
        self.label_VIBOR_MODEL.setObjectName("label_VIBOR_MODEL")
        self.gridLayout.addWidget(self.label_VIBOR_MODEL, 1, 0, 1, 1)
        self.comboBox_VIBOR_MODEL = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.comboBox_VIBOR_MODEL.setFont(font)
        self.comboBox_VIBOR_MODEL.setStyleSheet("QComboBox{\n"
"    background-color:white;\n"
"}\n"
"QComboBox:hover{\n"
"    border:1px solid rgb(5,142,215);\n"
"}\n"
"QComboBox:pressed{\n"
"    border:1px solid rgb(5,142,215);\n"
"}")
        self.comboBox_VIBOR_MODEL.setObjectName("comboBox_VIBOR_MODEL")
        self.comboBox_VIBOR_MODEL.addItem("")
        self.gridLayout.addWidget(self.comboBox_VIBOR_MODEL, 1, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_PARAMETRI_ANALITIKI)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 140, 321, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_VIVESTI_ANALITIKU_IS_BD = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_VIVESTI_ANALITIKU_IS_BD.setFont(font)
        self.pushButton_VIVESTI_ANALITIKU_IS_BD.setStyleSheet("QPushButton{\n"
"background-color: rgb(215, 215, 215);\n"
"border: 1px solid gray;\n"
"}\n"
"QPushButton:hover {border:2px solid  rgb(0, 120, 215);}\n"
"QPushButton:pressed {border:2px solid  rgb(0, 120, 215);}")
        self.pushButton_VIVESTI_ANALITIKU_IS_BD.setObjectName("pushButton_VIVESTI_ANALITIKU_IS_BD")
        self.horizontalLayout.addWidget(self.pushButton_VIVESTI_ANALITIKU_IS_BD)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Аналитика по живучести"))
        self.groupBox_PARAMETRI_ANALITIKI.setTitle(_translate("MainWindow", "Параметры аналитики"))
        self.comboBox_SORT_PO.setItemText(0, _translate("MainWindow", "По возрастанию"))
        self.comboBox_SORT_PO.setItemText(1, _translate("MainWindow", "По убыванию"))
        self.label_SORT_PO.setText(_translate("MainWindow", "Сортировать по"))
        self.label_VIBOR_MODEL.setText(_translate("MainWindow", "Выборка по модели"))
        self.comboBox_VIBOR_MODEL.setItemText(0, _translate("MainWindow", "Не выбрано"))
        self.pushButton_VIVESTI_ANALITIKU_IS_BD.setText(_translate("MainWindow", "Вывести аналитику"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_Jivuchest()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
