# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowSTART(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(400,600)
        MainWindow.setStyleSheet("background-color:rgb(245, 245, 245)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_BPLA = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_BPLA.setGeometry(QtCore.QRect(10, 10, 371, 211))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.groupBox_BPLA.setFont(font)
        self.groupBox_BPLA.setObjectName("groupBox_BPLA")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_BPLA)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 371, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_ADD_BPLA = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_ADD_BPLA.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_ADD_BPLA.setFont(font)
        self.pushButton_ADD_BPLA.setStyleSheet("QPushButton{\n"
"background-color: rgb(215, 215, 215);\n"
"border: 1px solid gray;\n"
"}\n"
"QPushButton:hover {border:2px solid  rgb(0, 120, 215);}\n"
"QPushButton:pressed {border:2px solid  rgb(0, 120, 215);}")
        self.pushButton_ADD_BPLA.setObjectName("pushButton_ADD_BPLA")
        self.horizontalLayout_4.addWidget(self.pushButton_ADD_BPLA)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_BPLA)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 60, 371, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_ViVESTI_BPLA = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_ViVESTI_BPLA.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_ViVESTI_BPLA.setFont(font)
        self.pushButton_ViVESTI_BPLA.setStyleSheet("QPushButton{\n"
"background-color: rgb(215, 215, 215);\n"
"border: 1px solid gray;\n"
"}\n"
"QPushButton:hover {border:2px solid  rgb(0, 120, 215);}\n"
"QPushButton:pressed {border:2px solid  rgb(0, 120, 215);}")
        self.pushButton_ViVESTI_BPLA.setObjectName("pushButton_ViVESTI_BPLA")
        self.horizontalLayout_5.addWidget(self.pushButton_ViVESTI_BPLA)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_BPLA)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 100, 371, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_DELETE_BPLA = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_DELETE_BPLA.setEnabled(False)
        self.pushButton_DELETE_BPLA.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_DELETE_BPLA.setFont(font)
        self.pushButton_DELETE_BPLA.setStyleSheet("QPushButton{\n"
"background-color: rgb(215, 215, 215);\n"
"border: 1px solid gray;\n"
"}\n"
"QPushButton:hover {border:2px solid  rgb(0, 120, 215);}\n"
"QPushButton:pressed {border:2px solid  rgb(0, 120, 215);}")
        self.pushButton_DELETE_BPLA.setObjectName("pushButton_DELETE_BPLA")
        self.horizontalLayout_6.addWidget(self.pushButton_DELETE_BPLA)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_BPLA)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 140, 371, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_CHANGE_BPLA = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_CHANGE_BPLA.setEnabled(False)
        self.pushButton_CHANGE_BPLA.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_CHANGE_BPLA.setFont(font)
        self.pushButton_CHANGE_BPLA.setStyleSheet("QPushButton{\n"
"background-color: rgb(215, 215, 215);\n"
"border: 1px solid gray;\n"
"}\n"
"QPushButton:hover {border:2px solid  rgb(0, 120, 215);}\n"
"QPushButton:pressed {border:2px solid  rgb(0, 120, 215);}")
        self.pushButton_CHANGE_BPLA.setObjectName("pushButton_CHANGE_BPLA")
        self.horizontalLayout_7.addWidget(self.pushButton_CHANGE_BPLA)
        self.groupBox_FLIGHTS = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_FLIGHTS.setGeometry(QtCore.QRect(10, 230, 371, 151))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.groupBox_FLIGHTS.setFont(font)
        self.groupBox_FLIGHTS.setObjectName("groupBox_FLIGHTS")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_FLIGHTS)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(0, 20, 371, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_ADD_FLIGHTS = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_ADD_FLIGHTS.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_ADD_FLIGHTS.setFont(font)
        self.pushButton_ADD_FLIGHTS.setStyleSheet("QPushButton{\n"
"background-color: rgb(215, 215, 215);\n"
"border: 1px solid gray;\n"
"}\n"
"QPushButton:hover {border:2px solid  rgb(0, 120, 215);}\n"
"QPushButton:pressed {border:2px solid  rgb(0, 120, 215);}")
        self.pushButton_ADD_FLIGHTS.setObjectName("pushButton_ADD_FLIGHTS")
        self.horizontalLayout_8.addWidget(self.pushButton_ADD_FLIGHTS)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_FLIGHTS)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(0, 60, 371, 41))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_VIVESTI_FLIGHTS = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.pushButton_VIVESTI_FLIGHTS.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_VIVESTI_FLIGHTS.setFont(font)
        self.pushButton_VIVESTI_FLIGHTS.setStyleSheet("QPushButton{\n"
"background-color: rgb(215, 215, 215);\n"
"border: 1px solid gray;\n"
"}\n"
"QPushButton:hover {border:2px solid  rgb(0, 120, 215);}\n"
"QPushButton:pressed {border:2px solid  rgb(0, 120, 215);}")
        self.pushButton_VIVESTI_FLIGHTS.setObjectName("pushButton_VIVESTI_FLIGHTS")
        self.horizontalLayout_9.addWidget(self.pushButton_VIVESTI_FLIGHTS)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.groupBox_FLIGHTS)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(0, 100, 371, 41))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_DELETE_FLIGHTS = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.pushButton_DELETE_FLIGHTS.setEnabled(False)
        self.pushButton_DELETE_FLIGHTS.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_DELETE_FLIGHTS.setFont(font)
        self.pushButton_DELETE_FLIGHTS.setStyleSheet("QPushButton{\n"
"background-color: rgb(215, 215, 215);\n"
"border: 1px solid gray;\n"
"}\n"
"QPushButton:hover {border:2px solid  rgb(0, 120, 215);}\n"
"QPushButton:pressed {border:2px solid  rgb(0, 120, 215);}")
        self.pushButton_DELETE_FLIGHTS.setObjectName("pushButton_DELETE_FLIGHTS")
        self.horizontalLayout_10.addWidget(self.pushButton_DELETE_FLIGHTS)
        self.groupBox_ANALITIKA = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_ANALITIKA.setGeometry(QtCore.QRect(10, 390, 371, 151))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.groupBox_ANALITIKA.setFont(font)
        self.groupBox_ANALITIKA.setObjectName("groupBox_ANALITIKA")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.groupBox_ANALITIKA)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(0, 20, 371, 41))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_EFFEKTIVNOST = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.pushButton_EFFEKTIVNOST.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_EFFEKTIVNOST.setFont(font)
        self.pushButton_EFFEKTIVNOST.setStyleSheet("QPushButton{\n"
"background-color: rgb(215, 215, 215);\n"
"border: 1px solid gray;\n"
"}\n"
"QPushButton:hover {border:2px solid  rgb(0, 120, 215);}\n"
"QPushButton:pressed {border:2px solid  rgb(0, 120, 215);}")
        self.pushButton_EFFEKTIVNOST.setObjectName("pushButton_EFFEKTIVNOST")
        self.horizontalLayout_11.addWidget(self.pushButton_EFFEKTIVNOST)
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.groupBox_ANALITIKA)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(0, 60, 371, 41))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_RESURSOZATRATNOST = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        self.pushButton_RESURSOZATRATNOST.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_RESURSOZATRATNOST.setFont(font)
        self.pushButton_RESURSOZATRATNOST.setStyleSheet("QPushButton{\n"
"background-color: rgb(215, 215, 215);\n"
"border: 1px solid gray;\n"
"}\n"
"QPushButton:hover {border:2px solid  rgb(0, 120, 215);}\n"
"QPushButton:pressed {border:2px solid  rgb(0, 120, 215);}")
        self.pushButton_RESURSOZATRATNOST.setObjectName("pushButton_RESURSOZATRATNOST")
        self.horizontalLayout_12.addWidget(self.pushButton_RESURSOZATRATNOST)
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.groupBox_ANALITIKA)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(0, 100, 371, 41))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_JIVUCHEST = QtWidgets.QPushButton(self.horizontalLayoutWidget_10)
        self.pushButton_JIVUCHEST.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_JIVUCHEST.setFont(font)
        self.pushButton_JIVUCHEST.setStyleSheet("QPushButton{\n"
"background-color: rgb(215, 215, 215);\n"
"border: 1px solid gray;\n"
"}\n"
"QPushButton:hover {border:2px solid  rgb(0, 120, 215);}\n"
"QPushButton:pressed {border:2px solid  rgb(0, 120, 215);}")
        self.pushButton_JIVUCHEST.setObjectName("pushButton_JIVUCHEST")
        self.horizontalLayout_13.addWidget(self.pushButton_JIVUCHEST)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 24))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.menu.setFont(font)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Тур 3"))
        self.groupBox_BPLA.setTitle(_translate("MainWindow", "БПЛА"))
        self.pushButton_ADD_BPLA.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_ViVESTI_BPLA.setText(_translate("MainWindow", "Вывести все"))
        self.pushButton_DELETE_BPLA.setText(_translate("MainWindow", "Удалить"))
        self.pushButton_CHANGE_BPLA.setText(_translate("MainWindow", "Изменить"))
        self.groupBox_FLIGHTS.setTitle(_translate("MainWindow", "Полеты"))
        self.pushButton_ADD_FLIGHTS.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_VIVESTI_FLIGHTS.setText(_translate("MainWindow", "Вывести все"))
        self.pushButton_DELETE_FLIGHTS.setText(_translate("MainWindow", "Удалить"))
        self.groupBox_ANALITIKA.setTitle(_translate("MainWindow", "Аналитика"))
        self.pushButton_EFFEKTIVNOST.setText(_translate("MainWindow", "Эффективность"))
        self.pushButton_RESURSOZATRATNOST.setText(_translate("MainWindow", "Ресурсозатратность"))
        self.pushButton_JIVUCHEST.setText(_translate("MainWindow", "Живучесть"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindowSTART()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
